/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    AM109_031_01_Chrome1_0: THREE.Mesh;
    ["armchair_Material_#36_0"]: THREE.Mesh;
    ["bath_walls_Material_#39_0"]: THREE.Mesh;
    ["Box008_Material_#71_0"]: THREE.Mesh;
    Box8418_Chrome_Satin_0: THREE.Mesh;
    Box8423_table_0: THREE.Mesh;
    Box8424_window_glass_0: THREE.Mesh;
    Box8425_def_0: THREE.Mesh;
    ["ceeling_Material_#50_0"]: THREE.Mesh;
    chainik_Chrome1_0: THREE.Mesh;
    chair_Chrome1_0: THREE.Mesh;
    chair001_Chrome1_0: THREE.Mesh;
    chrome_details_Chrome1_0: THREE.Mesh;
    Circle02_metall_light_0: THREE.Mesh;
    ["Cloth_Shape001577_Material_#45_0"]: THREE.Mesh;
    ["curtains_uvs_Material_#51_0"]: THREE.Mesh;
    Cylinder001_def_black_0: THREE.Mesh;
    ["Cylinder001_Material_#2097628050_0"]: THREE.Mesh;
    Cylinder025_20_0: THREE.Mesh;
    Cylinder14_Chrome1_0: THREE.Mesh;
    Cylinder19_black_plastic_0: THREE.Mesh;
    ["detal_0_18_Material_#61_0"]: THREE.Mesh;
    detal_0_6_vodootliv_0: THREE.Mesh;
    ["dining_table_Material_#52_0"]: THREE.Mesh;
    ["divan_brown_leather_Material_#48_0"]: THREE.Mesh;
    ["divan_white_cotton_Material_#54_0"]: THREE.Mesh;
    ["door_bath1_Material_#55_0"]: THREE.Mesh;
    doorstep_def_0: THREE.Mesh;
    ["electric_Material_#42_0"]: THREE.Mesh;
    ["entrance_door_Material_#56_0"]: THREE.Mesh;
    ["floor_Material_#57_0"]: THREE.Mesh;
    handle_06_Chrome1_0: THREE.Mesh;
    ["journal_Material_#58_0"]: THREE.Mesh;
    kitchen_axor_stark_kitchen_Chrome1_0: THREE.Mesh;
    ["kitchen_clear_Material_#59_0"]: THREE.Mesh;
    kitchen_conf_Chrome1_0: THREE.Mesh;
    ["kitchen_stoleshn_Material_#60_0"]: THREE.Mesh;
    kitchen_vitajka_Chrome1_0: THREE.Mesh;
    kithen_glass_plita_glass_0: THREE.Mesh;
    knopka_sliva_Chrome1_0: THREE.Mesh;
    kreplenie003_Chrome_Satin_0: THREE.Mesh;
    ["lamp_ab_Material_#2125638286_0"]: THREE.Mesh;
    ["lamp_above_table_Material_#43_0"]: THREE.Mesh;
    lamp_chrome_Chrome_Satin_0: THREE.Mesh;
    lampframe_ceeling01_def_0: THREE.Mesh;
    Line035_Chrome1_0: THREE.Mesh;
    mirror_mirror_0: THREE.Mesh;
    mirror_frame_frame_of_mirror_0: THREE.Mesh;
    obj_03_Chrome1_0: THREE.Mesh;
    object_def_0: THREE.Mesh;
    Object001732_def_0: THREE.Mesh;
    ["Object002_Material_#46_0"]: THREE.Mesh;
    Object1738_ceramics_0: THREE.Mesh;
    ["Object1739_Material_#64_0"]: THREE.Mesh;
    oras_Chrome1_0: THREE.Mesh;
    ["otkosy001_Material_#62_0"]: THREE.Mesh;
    Plane005_plane_za_divanom_0: THREE.Mesh;
    ["Plane03_Material_#41_0"]: THREE.Mesh;
    ["plinth_Material_#63_0"]: THREE.Mesh;
    provod_def_0: THREE.Mesh;
    ["radiator_inside2_Material_#2125638305_0"]: THREE.Mesh;
    ["radiator_polymesh_Material_#65_0"]: THREE.Mesh;
    rakovina_Chrome_Satin_0: THREE.Mesh;
    ["Ramki_2_Material_#35_0"]: THREE.Mesh;
    self_illum1_self_illum_0: THREE.Mesh;
    Sphere232_Chrome1_0: THREE.Mesh;
    Sphere233_def_0: THREE.Mesh;
    ["Sphere237_Material_#2125638307_0"]: THREE.Mesh;
    ["stellaj2_Material_#66_0"]: THREE.Mesh;
    stolik_stolik_0: THREE.Mesh;
    ["stul_sidenie_Material_#68_0"]: THREE.Mesh;
    ["stul_sidenie001_Material_#67_0"]: THREE.Mesh;
    sushilka_Chrome1_0: THREE.Mesh;
    ["Text005_Material_#82_0"]: THREE.Mesh;
    ["thermohead_Material_#69_0"]: THREE.Mesh;
    ["tv_glass_Material_#70_0"]: THREE.Mesh;
    ["Vaza_02_Material_#49_0"]: THREE.Mesh;
    ventil_metall_20_0: THREE.Mesh;
    ventil_metall_Chrome_Satin_0: THREE.Mesh;
    ["walls_clear_Material_#38_0"]: THREE.Mesh;
    ["window_Material_#72_0"]: THREE.Mesh;
    ["Yuciken_BATTHA_base_Material_#73_0"]: THREE.Mesh;
    Yuciken_BATTHA_cap_Yuciken_BATTHA_fase_0: THREE.Mesh;
    zamok_01_Chrome1_0: THREE.Mesh;
  };
  materials: {
    Chrome1: THREE.MeshBasicMaterial;
    Material_36: THREE.MeshBasicMaterial;
    Material_39: THREE.MeshBasicMaterial;
    Material_71: THREE.MeshBasicMaterial;
    Chrome_Satin: THREE.MeshBasicMaterial;
    table: THREE.MeshBasicMaterial;
    window_glass: THREE.MeshBasicMaterial;
    ["material.001"]: THREE.MeshBasicMaterial;
    Material_50: THREE.MeshBasicMaterial;
    metall_light: THREE.MeshBasicMaterial;
    Material_45: THREE.MeshBasicMaterial;
    Material_51: THREE.MeshBasicMaterial;
    def_black: THREE.MeshBasicMaterial;
    Material_2097628050: THREE.MeshBasicMaterial;
    material_20: THREE.MeshBasicMaterial;
    black_plastic: THREE.MeshBasicMaterial;
    Material_61: THREE.MeshBasicMaterial;
    vodootliv: THREE.MeshBasicMaterial;
    Material_52: THREE.MeshBasicMaterial;
    Material_48: THREE.MeshBasicMaterial;
    Material_54: THREE.MeshBasicMaterial;
    Material_55: THREE.MeshBasicMaterial;
    Material_42: THREE.MeshBasicMaterial;
    Material_56: THREE.MeshBasicMaterial;
    Material_57: THREE.MeshBasicMaterial;
    Material_58: THREE.MeshBasicMaterial;
    Material_59: THREE.MeshBasicMaterial;
    Material_60: THREE.MeshBasicMaterial;
    plita_glass: THREE.MeshBasicMaterial;
    Material_2125638286: THREE.MeshBasicMaterial;
    Material_43: THREE.MeshBasicMaterial;
    mirror: THREE.MeshBasicMaterial;
    frame_of_mirror: THREE.MeshBasicMaterial;
    Material_46: THREE.MeshBasicMaterial;
    ceramics: THREE.MeshBasicMaterial;
    Material_64: THREE.MeshBasicMaterial;
    Material_62: THREE.MeshBasicMaterial;
    plane_za_divanom: THREE.MeshBasicMaterial;
    Material_41: THREE.MeshBasicMaterial;
    Material_63: THREE.MeshBasicMaterial;
    Material_2125638305: THREE.MeshBasicMaterial;
    Material_65: THREE.MeshBasicMaterial;
    Material_35: THREE.MeshBasicMaterial;
    self_illum: THREE.MeshBasicMaterial;
    Material_2125638307: THREE.MeshBasicMaterial;
    Material_66: THREE.MeshBasicMaterial;
    stolik: THREE.MeshBasicMaterial;
    Material_68: THREE.MeshBasicMaterial;
    Material_67: THREE.MeshBasicMaterial;
    Material_82: THREE.MeshBasicMaterial;
    Material_69: THREE.MeshBasicMaterial;
    Material_70: THREE.MeshBasicMaterial;
    Material_49: THREE.MeshBasicMaterial;
    Material_38: THREE.MeshBasicMaterial;
    Material_72: THREE.MeshBasicMaterial;
    Material_73: THREE.MeshBasicMaterial;
    Yuciken_BATTHA_fase: THREE.MeshBasicMaterial;
  };
};

export function Apartment(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/environment/studio_apartment.gltf") as GLTFResult;

    // set environment intensity for every object

    // let k: keyof typeof materials;  
    // for (k in materials) {
    //   const v = materials[k];  
    //   v.envMapIntensity = 0.1
    // }
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.AM109_031_01_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes["armchair_Material_#36_0"].geometry}
        material={materials.Material_36}
      />
      <mesh
        geometry={nodes["bath_walls_Material_#39_0"].geometry}
        material={materials.Material_39}
      />
      <mesh
        geometry={nodes["Box008_Material_#71_0"].geometry}
        material={materials.Material_71}
      />
      <mesh
        geometry={nodes.Box8418_Chrome_Satin_0.geometry}
        material={materials.Chrome_Satin}
      />
      <mesh
        geometry={nodes.Box8423_table_0.geometry}
        material={materials.table}
      />
      <mesh
        geometry={nodes.Box8424_window_glass_0.geometry}
        material={materials.window_glass}
      />
      <mesh
        geometry={nodes.Box8425_def_0.geometry}
        material={materials["material.001"]}
      />
      <mesh
        geometry={nodes["ceeling_Material_#50_0"].geometry}
        material={materials.Material_50}
      />
      <mesh
        geometry={nodes.chainik_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.chair_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.chair001_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.chrome_details_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.Circle02_metall_light_0.geometry}
        material={materials.metall_light}
      />
      <mesh
        geometry={nodes["Cloth_Shape001577_Material_#45_0"].geometry}
        material={materials.Material_45}
      />
      <mesh
        geometry={nodes["curtains_uvs_Material_#51_0"].geometry}
        material={materials.Material_51}
      />
      <mesh
        geometry={nodes.Cylinder001_def_black_0.geometry}
        material={materials.def_black}
      />
      <mesh
        geometry={nodes["Cylinder001_Material_#2097628050_0"].geometry}
        material={materials.Material_2097628050}
      />
      <mesh
        geometry={nodes.Cylinder025_20_0.geometry}
        material={materials.material_20}
      />
      <mesh
        geometry={nodes.Cylinder14_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.Cylinder19_black_plastic_0.geometry}
        material={materials.black_plastic}
      />
      <mesh
        geometry={nodes["detal_0_18_Material_#61_0"].geometry}
        material={materials.Material_61}
      />
      <mesh
        geometry={nodes.detal_0_6_vodootliv_0.geometry}
        material={materials.vodootliv}
      />
      <mesh
        geometry={nodes["dining_table_Material_#52_0"].geometry}
        material={materials.Material_52}
      />
      <mesh
        geometry={nodes["divan_brown_leather_Material_#48_0"].geometry}
        material={materials.Material_48}
      />
      <mesh
        geometry={nodes["divan_white_cotton_Material_#54_0"].geometry}
        material={materials.Material_54}
      />
      <mesh
        geometry={nodes["door_bath1_Material_#55_0"].geometry}
        material={materials.Material_55}
      />
      <mesh
        geometry={nodes.doorstep_def_0.geometry}
        material={materials["material.001"]}
      />
      <mesh
        geometry={nodes["electric_Material_#42_0"].geometry}
        material={materials.Material_42}
      />
      <mesh
        geometry={nodes["entrance_door_Material_#56_0"].geometry}
        material={materials.Material_56}
      />
      <mesh
        geometry={nodes["floor_Material_#57_0"].geometry}
        material={materials.Material_57}
      />
      <mesh
        geometry={nodes.handle_06_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes["journal_Material_#58_0"].geometry}
        material={materials.Material_58}
      />
      <mesh
        geometry={nodes.kitchen_axor_stark_kitchen_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes["kitchen_clear_Material_#59_0"].geometry}
        material={materials.Material_59}
      />
      <mesh
        geometry={nodes.kitchen_conf_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes["kitchen_stoleshn_Material_#60_0"].geometry}
        material={materials.Material_60}
      />
      <mesh
        geometry={nodes.kitchen_vitajka_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.kithen_glass_plita_glass_0.geometry}
        material={materials.plita_glass}
      />
      <mesh
        geometry={nodes.knopka_sliva_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.kreplenie003_Chrome_Satin_0.geometry}
        material={materials.Chrome_Satin}
      />
      <mesh
        geometry={nodes["lamp_ab_Material_#2125638286_0"].geometry}
        material={materials.Material_2125638286}
      />
      <mesh
        geometry={nodes["lamp_above_table_Material_#43_0"].geometry}
        material={materials.Material_43}
      />
      <mesh
        geometry={nodes.lamp_chrome_Chrome_Satin_0.geometry}
        material={materials.Chrome_Satin}
      />
      <mesh
        geometry={nodes.lampframe_ceeling01_def_0.geometry}
        material={materials["material.001"]}
      />
      <mesh
        geometry={nodes.Line035_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.mirror_mirror_0.geometry}
        material={materials.mirror}
      />
      <mesh
        geometry={nodes.mirror_frame_frame_of_mirror_0.geometry}
        material={materials.frame_of_mirror}
      />
      <mesh
        geometry={nodes.obj_03_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.object_def_0.geometry}
        material={materials["material.001"]}
      />
      <mesh
        geometry={nodes.Object001732_def_0.geometry}
        material={materials["material.001"]}
      />
      <mesh
        geometry={nodes["Object002_Material_#46_0"].geometry}
        material={materials.Material_46}
      />
      <mesh
        geometry={nodes.Object1738_ceramics_0.geometry}
        material={materials.ceramics}
      />
      <mesh
        geometry={nodes["Object1739_Material_#64_0"].geometry}
        material={materials.Material_64}
      />
      <mesh
        geometry={nodes.oras_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes["otkosy001_Material_#62_0"].geometry}
        material={materials.Material_62}
      />
      <mesh
        geometry={nodes.Plane005_plane_za_divanom_0.geometry}
        material={materials.plane_za_divanom}
      />
      <mesh
        geometry={nodes["Plane03_Material_#41_0"].geometry}
        material={materials.Material_41}
      />
      <mesh
        geometry={nodes["plinth_Material_#63_0"].geometry}
        material={materials.Material_63}
      />
      <mesh
        geometry={nodes.provod_def_0.geometry}
        material={materials["material.001"]}
      />
      <mesh
        geometry={nodes["radiator_inside2_Material_#2125638305_0"].geometry}
        material={materials.Material_2125638305}
      />
      <mesh
        geometry={nodes["radiator_polymesh_Material_#65_0"].geometry}
        material={materials.Material_65}
      />
      <mesh
        geometry={nodes.rakovina_Chrome_Satin_0.geometry}
        material={materials.Chrome_Satin}
      />
      <mesh
        geometry={nodes["Ramki_2_Material_#35_0"].geometry}
        material={materials.Material_35}
      />
      <mesh
        geometry={nodes.self_illum1_self_illum_0.geometry}
        material={materials.self_illum}
      />
      <mesh
        geometry={nodes.Sphere232_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes.Sphere233_def_0.geometry}
        material={materials["material.001"]}
      />
      <mesh
        geometry={nodes["Sphere237_Material_#2125638307_0"].geometry}
        material={materials.Material_2125638307}
      />
      <mesh
        geometry={nodes["stellaj2_Material_#66_0"].geometry}
        material={materials.Material_66}
      />
      <mesh
        geometry={nodes.stolik_stolik_0.geometry}
        material={materials.stolik}
      />
      <mesh
        geometry={nodes["stul_sidenie_Material_#68_0"].geometry}
        material={materials.Material_68}
      />
      <mesh
        geometry={nodes["stul_sidenie001_Material_#67_0"].geometry}
        material={materials.Material_67}
      />
      <mesh
        geometry={nodes.sushilka_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
      <mesh
        geometry={nodes["Text005_Material_#82_0"].geometry}
        material={materials.Material_82}
      />
      <mesh
        geometry={nodes["thermohead_Material_#69_0"].geometry}
        material={materials.Material_69}
      />
      <mesh
        geometry={nodes["tv_glass_Material_#70_0"].geometry}
        material={materials.Material_70}
      />
      <mesh
        geometry={nodes["Vaza_02_Material_#49_0"].geometry}
        material={materials.Material_49}
      />
      <mesh
        geometry={nodes.ventil_metall_20_0.geometry}
        material={materials.material_20}
      />
      <mesh
        geometry={nodes.ventil_metall_Chrome_Satin_0.geometry}
        material={materials.Chrome_Satin}
      />
      <mesh
        geometry={nodes["walls_clear_Material_#38_0"].geometry}
        material={materials.Material_38}
      />
      <mesh
        geometry={nodes["window_Material_#72_0"].geometry}
        material={materials.Material_72}
      />
      <mesh
        geometry={nodes["Yuciken_BATTHA_base_Material_#73_0"].geometry}
        material={materials.Material_73}
      />
      <mesh
        geometry={nodes.Yuciken_BATTHA_cap_Yuciken_BATTHA_fase_0.geometry}
        material={materials.Yuciken_BATTHA_fase}
      />
      <mesh
        geometry={nodes.zamok_01_Chrome1_0.geometry}
        material={materials.Chrome1}
      />
    </group>
  );
}

useGLTF.preload("/environment/studio_apartment.gltf");
