/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Box013_Material_#2146801999_0"]: THREE.Mesh;
    ["Object001_Material_#2146802003_0"]: THREE.Mesh;
    ["Object350_Material_#2146801996_0"]: THREE.Mesh;
    ["Object355_Material_#2146802006_0"]: THREE.Mesh;
    ["Object347_Material_#2146802338_0"]: THREE.Mesh;
  };
  materials: {
    Material_2146801999: THREE.MeshStandardMaterial;
    Material_2146802003: THREE.MeshStandardMaterial;
    Material_2146801996: THREE.MeshStandardMaterial;
    Material_2146802006: THREE.MeshStandardMaterial;
    Material_2146802338: THREE.MeshStandardMaterial;
  };
};

export function Flat(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/environment/apartment.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Box013_Material_#2146801999_0"].geometry}
        material={materials.Material_2146801999}
      />
      <mesh
        geometry={nodes["Object001_Material_#2146802003_0"].geometry}
        material={materials.Material_2146802003}
      />
      <mesh
        geometry={nodes["Object350_Material_#2146801996_0"].geometry}
        material={materials.Material_2146801996}
      />
      <mesh
        geometry={nodes["Object355_Material_#2146802006_0"].geometry}
        material={materials.Material_2146802006}
      />
      <mesh
        geometry={nodes["Object347_Material_#2146802338_0"].geometry}
        material={materials.Material_2146802338}
      />
    </group>
  );
}

useGLTF.preload("/environment/apartment.gltf");
