/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    AbstractArt_AbstractArt_0: THREE.Mesh;
    CoffeeTable_CoffeeTable_0: THREE.Mesh;
    Lamp_Lamp_0: THREE.Mesh;
    PictureFrame_Material_0: THREE.Mesh;
    Pillows_Pillows_0: THREE.Mesh;
    Plant__0: THREE.Mesh;
    Sofa_Sofa_0: THREE.Mesh;
    Structure_Structure_0: THREE.Mesh;
    TV_TV_0: THREE.Mesh;
    TVStand_TVStand_0: THREE.Mesh;
  };
  materials: {
    ["AbstractArt.001"]: THREE.MeshStandardMaterial;
    ["CoffeeTable.001"]: THREE.MeshStandardMaterial;
    ["Lamp.001"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Pillows.001"]: THREE.MeshStandardMaterial;
    Plant__0: THREE.MeshStandardMaterial;
    ["Sofa.001"]: THREE.MeshStandardMaterial;
    ["Structure.001"]: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    ["TVStand.001"]: THREE.MeshStandardMaterial;
  };
};

export function ModernRoom(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/environment/modern_room.gltf"
  ) as GLTFResult;


  // set environment intensity for every object

  let k: keyof typeof materials;  
  for (k in materials) {
    const v = materials[k];  
    v.envMapIntensity = 0.1
  }

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.177, 0]} scale={0.47}>
        <mesh
          geometry={nodes.AbstractArt_AbstractArt_0.geometry}
          material={materials["AbstractArt.001"]}
          position={[-37.161, 18.38, 0.278]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[4.734, 4.734, 7.575]}
        />
        <mesh
          geometry={nodes.CoffeeTable_CoffeeTable_0.geometry}
          material={materials["CoffeeTable.001"]}
          position={[-2.785, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.785}
        />
        <group  position={[-25.064, 0, -25.064]}>
          <mesh
            geometry={nodes.Lamp_Lamp_0.geometry}
            material={materials["Lamp.001"]}

            rotation={[-Math.PI / 2, 0, -Math.PI / 9]}
            scale={2.785}
          />
        <pointLight intensity={0.3} position={[5.6, 18, 2.3]} />

        </group>

        <mesh
          geometry={nodes.PictureFrame_Material_0.geometry}
          material={materials["Material.001"]}
          position={[-33.872, 22.355, 13.367]}
          rotation={[-Math.PI / 2, -0.175, 0]}
          scale={1.671}
        />
        <mesh
          geometry={nodes.Pillows_Pillows_0.geometry}
          material={materials["Pillows.001"]}
          position={[-22.455, 4.095, 21.241]}
          rotation={[-Math.PI / 2, 1.396, 0]}
          scale={[2.247, 2.785, 2.77]}
        />
        <mesh
          geometry={nodes.Plant__0.geometry}
          material={materials.Plant__0}
          position={[-31.644, 17.67, 19.458]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.749}
        />
        <mesh
          geometry={nodes.Sofa_Sofa_0.geometry}
          material={materials["Sofa.001"]}
          position={[-25.064, -0.812, 23.61]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.785}
        />
        <mesh
          geometry={nodes.Structure_Structure_0.geometry}
          material={materials["Structure.001"]}
          position={[0, 22.279, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[32.717, 29.99, 24.785]}
        />
        <mesh
          geometry={nodes.TV_TV_0.geometry}
          material={materials.material}
          position={[5.57, 16.709, -30.485]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[-12.532, -0.696, -6.962]}
        />
        <mesh
          geometry={nodes.TVStand_TVStand_0.geometry}
          material={materials["TVStand.001"]}
          position={[5.57, 0, -29.947]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[13.089, 3.063, 2.785]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/environment/modern_room.gltf");
